export const PROCESSING_STATUS_UPLOADED = "uploaded";
export const PROCESSING_STATUS_READ = "read";
export const PROCESSING_FINISHED_STATUS = "enriched";
export const PROCESSING_STATUS_ERROR = "error";

export const PROCESSING_STEPS = [
  PROCESSING_STATUS_UPLOADED,
  PROCESSING_STATUS_READ,
  PROCESSING_FINISHED_STATUS,
];
