// TODO: P2: Fix redundant envs
const {
  COSMOS_DATABASE,
  COSMOS_RAW_CONTAINER,
  COSMOS_ENRICHED_CONTAINER,
  DI_ENDPOINT,
  DI_KEY,
  TEMP_USER_ID,
  OPENAI_ASSISTANT_ID,
  DISCORD_WEBHOOK_ID,
  DISCORD_WEBHOOK_TOKEN,
  WEB_BASE_URL,
  REVALIDATE_SECRET,
  COSMOS_PROCESSING_BUNDLE_CONTAINER,
  COSMOS_ENDPOINT,
  COSMOS_KEY,
} = process.env;

if (
  !COSMOS_DATABASE ||
  !COSMOS_RAW_CONTAINER ||
  !COSMOS_ENRICHED_CONTAINER ||
  !DI_ENDPOINT ||
  !DI_KEY ||
  !TEMP_USER_ID ||
  !OPENAI_ASSISTANT_ID ||
  !DISCORD_WEBHOOK_ID ||
  !DISCORD_WEBHOOK_TOKEN ||
  !WEB_BASE_URL ||
  !REVALIDATE_SECRET ||
  !COSMOS_PROCESSING_BUNDLE_CONTAINER ||
  !COSMOS_ENDPOINT ||
  !COSMOS_KEY
) {
  throw new Error("Missing environment variables");
}

export const config = {
  COSMOS_DATABASE,
  COSMOS_RAW_CONTAINER,
  COSMOS_ENRICHED_CONTAINER,
  DI_ENDPOINT,
  DI_KEY,
  TEMP_USER_ID,
  OPENAI_ASSISTANT_ID,
  DISCORD_WEBHOOK_ID,
  DISCORD_WEBHOOK_TOKEN,
  WEB_BASE_URL,
  REVALIDATE_SECRET,
  COSMOS_PROCESSING_BUNDLE_CONTAINER,
  COSMOS_ENDPOINT,
  COSMOS_KEY,
} as const;
